include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
  language:
    strict-inference: true

linter:
  rules:
    no_dynamic_casts: true
    no_raw_types: true
