name: hikari
description: "A cross-platform Flutter media hub for video, manga/comics/webtoon, and novels."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  archive: 4.3.0
  xml: 7.1.0
  html: 0.15.7
  flutter_widget_from_html_core: 0.17.4
  drift: 2.35.1
  drift_flutter: 0.3.1
  crypto: 3.0.7
  path: 1.9.1
  path_provider: 2.1.6
  media_kit: 1.2.6
  media_kit_libs_video: 1.0.7
  media_kit_video: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: 2.35.0
  build_runner: 2.16.1

flutter:
  uses-material-design: true
