package app.openstory.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val HikariLightColorScheme = lightColorScheme(
    primary = Color(0xFFC94C40),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDAD5),
    onPrimaryContainer = Color(0xFF3B0905),
    secondary = Color(0xFF2A786F),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFC9E9E3),
    onSecondaryContainer = Color(0xFF08201D),
    tertiary = Color(0xFF6B6658),
    onTertiary = Color.White,
    background = Color.White,
    onBackground = Color(0xFF211A18),
    surface = Color(0xFFFFF9F6),
    onSurface = Color(0xFF211A18),
    surfaceVariant = Color(0xFFF0E7E3),
    onSurfaceVariant = Color(0xFF6A605D),
    surfaceBright = Color(0xFFFFF9F6),
    surfaceDim = Color(0xFFE5DCD7),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFFAF4F1),
    surfaceContainer = Color(0xFFF5EFEB),
    surfaceContainerHigh = Color(0xFFEFE8E4),
    surfaceContainerHighest = Color(0xFFE9E1DD),
    outline = Color(0xFF8D7F7B),
    outlineVariant = Color(0xFFD8CBC6),
    error = Color(0xFFBA1A1A),
)

internal val HikariDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFF8E80),
    onPrimary = Color(0xFF4B0E08),
    primaryContainer = Color(0xFF653028),
    onPrimaryContainer = Color(0xFFFFDAD5),
    secondary = Color(0xFF8ED8CC),
    onSecondary = Color(0xFF003832),
    secondaryContainer = Color(0xFF185149),
    onSecondaryContainer = Color(0xFFACEFE4),
    tertiary = Color(0xFFCFC7B1),
    onTertiary = Color(0xFF353025),
    background = Color.Black,
    onBackground = Color(0xFFF5F1F0),
    surface = Color(0xFF121217),
    onSurface = Color(0xFFF5F1F0),
    surfaceVariant = Color(0xFF24242E),
    onSurfaceVariant = Color(0xFFC9C2C0),
    surfaceBright = Color(0xFF2B2B36),
    surfaceDim = Color(0xFF0B0B0F),
    surfaceContainerLowest = Color(0xFF0B0B0F),
    surfaceContainerLow = Color(0xFF111116),
    surfaceContainer = Color(0xFF17171D),
    surfaceContainerHigh = Color(0xFF1D1D25),
    surfaceContainerHighest = Color(0xFF24242E),
    outline = Color(0xFF9B9290),
    outlineVariant = Color(0xFF423B3D),
    error = Color(0xFFFFB4AB),
)
