package app.openstory.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val HikariLightColorScheme = lightColorScheme(
    primary = Color(0xFFF4515B),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFECEB),
    onPrimaryContainer = Color(0xFF410006),
    secondary = Color(0xFF2A9D8F),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFE2F4F1),
    onSecondaryContainer = Color(0xFF053530),
    tertiary = Color(0xFF6B6658),
    onTertiary = Color.White,
    background = Color.White,
    onBackground = Color(0xFF211A18),
    surface = Color(0xFFFFF9F7),
    onSurface = Color(0xFF211A18),
    surfaceVariant = Color(0xFFF2ECE9),
    onSurfaceVariant = Color(0xFF726662),
    surfaceBright = Color(0xFFFFF9F7),
    surfaceDim = Color(0xFFE5DDD9),
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFFAF5F2),
    surfaceContainer = Color(0xFFF6F0EC),
    surfaceContainerHigh = Color(0xFFEFE7E3),
    surfaceContainerHighest = Color(0xFFE8DFDB),
    outline = Color(0xFF8D7F7B),
    outlineVariant = Color(0xFFD8CBC6),
    error = Color(0xFFBA1A1A),
)

internal val HikariDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFF7078),
    onPrimary = Color(0xFF4B0E08),
    primaryContainer = Color(0xFF7D1B24),
    onPrimaryContainer = Color(0xFFFFDAD9),
    secondary = Color(0xFF6BD4C4),
    onSecondary = Color(0xFF003832),
    secondaryContainer = Color(0xFF1B534B),
    onSecondaryContainer = Color(0xFFACEFE4),
    tertiary = Color(0xFFCFC7B1),
    onTertiary = Color(0xFF353025),
    background = Color.Black,
    onBackground = Color(0xFFF5F1F0),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFF5F1F0),
    surfaceVariant = Color(0xFF252530),
    onSurfaceVariant = Color(0xFFCAC3C1),
    surfaceBright = Color(0xFF2C2C38),
    surfaceDim = Color(0xFF0B0B0F),
    surfaceContainerLowest = Color(0xFF0B0B0F),
    surfaceContainerLow = Color(0xFF111116),
    surfaceContainer = Color(0xFF181820),
    surfaceContainerHigh = Color(0xFF1F1F29),
    surfaceContainerHighest = Color(0xFF252530),
    outline = Color(0xFF9B9290),
    outlineVariant = Color(0xFF423B3D),
    error = Color(0xFFFFB4AB),
)
