import {build} from 'esbuild';
import {mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve, join} from 'node:path';
const root = dirname(fileURLToPath(import.meta.url));
const output = resolve(root,'../../android/app/src/main/assets/lnreader');
mkdirSync(output,{recursive:true});
const result=await build({absWorkingDir:root,entryPoints:['host.js'],bundle:true,
  platform:'browser',format:'iife',target:'es2020',minify:true,legalComments:'eof',metafile:true,
  outfile:join(output,'host.js')});
const packages=new Set();
for(const input of Object.keys(result.metafile.inputs)) {
 if(!input.includes('node_modules/'))continue;
 let dir=dirname(resolve(root,input));
 while(!existsSync(join(dir,'package.json')))dir=dirname(dir);
 // Nested ESM directories may carry only a type marker; climb to named package.
 while(!JSON.parse(readFileSync(join(dir,'package.json'),'utf8')).name) {
  dir=dirname(dir); while(!existsSync(join(dir,'package.json')))dir=dirname(dir);
 }
 packages.add(dir);
}
let notices='Bundled LNReader host JavaScript dependencies (generated by tool/lnreader/build.mjs)\n';
for(const dir of [...packages].sort()) {
 const pkg=JSON.parse(readFileSync(join(dir,'package.json'),'utf8'));
 const license=readdirSync(dir).find(name=>/^licen[sc]e(?:\..*)?$/i.test(name));
 const licensePath=license?join(dir,license):join(root,'licenses',pkg.name+'.txt');
 if(!existsSync(licensePath))throw Error('Missing license: '+pkg.name);
 notices+='\n=== '+pkg.name+' '+pkg.version+' ('+pkg.license+') ===\n'+readFileSync(licensePath,'utf8')+'\n';
}
writeFileSync(join(output,'THIRD_PARTY_LICENSES.txt'),notices);
